package com.cubesolve.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * JPA entity representing one solve attempt stored in the database.
 */
@Entity
@Table(name = "solve_records")
public class SolveRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The scrambled cube state as a comma-separated 54-integer string.
     */
    @Column(name = "cube_state", nullable = false, columnDefinition = "TEXT")
    private String cubeState;

    /**
     * The scramble that was applied (if generated by the app), or null if manually entered.
     */
    @Column(name = "scramble_moves", columnDefinition = "TEXT")
    private String scrambleMoves;

    /**
     * The solution move sequence returned by the solver.
     */
    @Column(name = "solution_moves", nullable = false, columnDefinition = "TEXT")
    private String solutionMoves;

    /**
     * Total number of moves in the solution.
     */
    @Column(name = "move_count", nullable = false)
    private int moveCount;

    /**
     * Time taken to compute the solution in milliseconds.
     */
    @Column(name = "solve_time_ms")
    private long solveTimeMs;

    /**
     * The user who requested this solve. Null for anonymous solves.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    public SolveRecord() { }

    // -------------------------------------------------------------------------
    // Getters & Setters
    // -------------------------------------------------------------------------

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getCubeState() { return cubeState; }
    public void setCubeState(String cubeState) { this.cubeState = cubeState; }

    public String getScrambleMoves() { return scrambleMoves; }
    public void setScrambleMoves(String scrambleMoves) { this.scrambleMoves = scrambleMoves; }

    public String getSolutionMoves() { return solutionMoves; }
    public void setSolutionMoves(String solutionMoves) { this.solutionMoves = solutionMoves; }

    public int getMoveCount() { return moveCount; }
    public void setMoveCount(int moveCount) { this.moveCount = moveCount; }

    public long getSolveTimeMs() { return solveTimeMs; }
    public void setSolveTimeMs(long solveTimeMs) { this.solveTimeMs = solveTimeMs; }

    public User getUser() { return user; }
    public void setUser(User user) { this.user = user; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
